# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # configure resolvers
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    filter_sets:
        cache : ~
        thumbnail_atropos_bg:
            quality: 75
            filters:
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [565, 318]
                    # crop the input image, if required
                    mode: outbound
        thumbnail_atropos_character:
            quality: 75
            filters:
                scale:
                    to: 0.3          
        thumbnail_atropos_text:
            quality: 80
            filters:
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [ 450, 191 ]
                    # crop the input image, if required
                    mode: outbound
        thumbnail_locked:
            quality: 75
            filters:
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [ 570, 300 ]
                    # crop the input image, if required
                    mode: outbound
