twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
        video_dir: '%video_dir%'
        image_dir: '%image_dir%'
        form_themes:
            - '@FontAwesome/fontawesome_layout.html.twig'

when@test:
    twig:
        strict_variables: true

