vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        video_file:
            uri_prefix: /videos/
            upload_destination: '%kernel.project_dir%/public/%video_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image_file:
            uri_prefix: /images/
            upload_destination: '%kernel.project_dir%/public/%image_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
