controllers:
    resource: ../src/Controller/
    exclude: ../src/Controller/Admin
    type: annotation

admin:
    resource: ../src/Controller/Admin
    type: attribute
    name_prefix: 'admin_'
    
kernel:
    resource: ../src/Kernel.php
    type: annotation
